# Generated by Django 4.2.2 on 2023-06-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.CharField(max_length=50)),
                ('moves', models.CharField(max_length=200)),
                ('player1', models.CharField(max_length=50)),
                ('player2', models.CharField(max_length=50)),
            ],
        ),
    ]
