# Generated by Django 4.2.2 on 2023-06-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_alter_game_player1_alter_game_player2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='id1',
            new_name='i_d',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2',
        ),
        migrations.AlterField(
            model_name='game',
            name='moves',
            field=models.CharField(max_length=1000),
        ),
    ]
