# Generated by Django 4.2.2 on 2023-06-21 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('play', '0003_rename_id1_game_i_d_remove_game_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_waiting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL),
        ),
    ]
