# Generated by Django 4.2.2 on 2023-06-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_alter_game_player1_alter_game_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='i_d',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
