# Generated by Django 4.2.2 on 2023-06-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_alter_game_i_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='i_d',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_waiting',
        ),
    ]
