# Generated by Django 4.2.2 on 2023-06-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0007_remove_game_i_d_remove_game_is_waiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player2',
        ),
    ]
