# Generated by Django 4.2.2 on 2023-06-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0009_remove_game_player1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='moves',
        ),
    ]
